replicaCount: 2

image:
  repository: xalien073/tmr
  tag: 82
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 3000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
