apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: tmr
  name: next-service-ingress  # Replace with the name for your ingress
spec:
  ingressClassName: azure-application-gateway  # Replace with your ingress class if different
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tmr-next-service  # Replace with your service name (matches your service.yaml)
                port:
                  number: 80  # Port exposed by your service (matches your service.yaml)


