apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-next-service
  labels:
    app: next-app
spec:
  selector:
    app: next-app
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
