apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: next-service-ingress
spec:
  ingressClassName: nginx  # Using Nginx now
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-service
                port:
                  number: 80
